apiVersion: apps/v1
kind: Deployment
metadata:
  name: student-deployment
  labels:
    app: student-application
spec:
  replicas: 1
  selector:
    matchLabels:
      app: student-application
  template:
    metadata:
      labels:
        app: student-application
    spec:
      containers:
        - name: spring-boot-app
          imagePullPolicy: Never
          image: us-central1-docker.pkg.dev/studentproject-393806/codelabrepo/hello-students:1.0
          ports:
            - containerPort: 8080